version: '3.7'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT}
    depends_on:
      - mysql
      - redis
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${SERVER_VOLUME_ROOT}
    networks:
      - nest-networks

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - ${MYSQL_PORT}
    volumes:
      - ${MYSQL_VOLUMES_ROOT}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - nest-networks

  redis:
    image: redis:latest
    ports:
      - ${REDIS_PORT}
    volumes:
      - ${REDIS_VOLUMES_ROOT}
    networks:
      - nest-networks
networks:
  nest-networks:
    driver: bridge
