version: '3.7'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${SERVER_NAME}
    ports:
      - 3000:3000
    depends_on:
      - mysql
      # - redis
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ${SERVER_VOLUME_ROOT}
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - server-net

  mysql:
    image: mysql:5.7
    container_name: ${MYSQL_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - 3306:3306
    volumes:
      - ${MYSQL_VOLUMES_ROOT}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - server-net

  # redis:
  #   image: redis:latest
  #   container_name: ${REDIS_NAME}
  #   ports:
  #     - ${REDIS_PORT}
  #   volumes:
  #     - ${REDIS_VOLUMES_ROOT}
  #   networks:
  #     - server-net
  #   extra_hosts:
  #     - host.docker.internal:host-gateway

networks:
  server-net:
    driver: bridge
