version: '3.7'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${SERVER_NAME}
    env_file:
      - ${SERVER_ENV}
    restart: always
    ports:
      - ${SERVER_PORT}
    depends_on:
      - mysql
      - redis
    volumes:
      - ${SERVER_VOLUME_ROOT}
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      server-net:
        ipv4_address: ${SERVER_IP}

  mysql:
    image: mysql:latest
    container_name: ${MYSQL_NAME}
    restart: always
    env_file:
      - ${MYSQL_ENV}
    ports:
      - ${MYSQL_PORT}
    volumes:
      - ${MYSQL_VOLUMES_ROOT}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      server-net:
        ipv4_address: ${MYSQL_IP}

  redis:
    image: redis:latest
    container_name: ${REDIS_NAME}
    restart: always
    env_file:
      - ${REDIS_ENV}
    ports:
      - ${REDIS_PORT}
    volumes:
      - ${REDIS_VOLUMES_ROOT}
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      server-net:
        ipv4_address: ${REDIS_IP}

networks:
  server-net:
    name: ${NETWORK_NAME}
    ipam:
      config:
        - subnet: ${SUBNET_IP}
